---
hostname: R4
loopback0_ipv4: 10.255.255.4/32
loopback0_ipv6: 2001:db8:ffff::4/128
interfaces:
- name: GigabitEthernet0/1
  description: Enlace a R3 (link 3)
  ipv4_address: 10.0.3.2
  ipv4_mask: 255.255.255.252
  ipv6_address: 2001:db8:3::2/64
- name: GigabitEthernet0/2
  description: Enlace a R1 (link 4)
  ipv4_address: 10.0.4.2
  ipv4_mask: 255.255.255.252
  ipv6_address: 2001:db8:4::2/64
- name: GigabitEthernet0/3
  description: Enlace a R7 (link 11)
  ipv4_address: 10.0.11.2
  ipv4_mask: 255.255.255.252
  ipv6_address: 2001:db8:11::2/64
